[package]
name = "arcade-rs"
version = "0.1.0"
authors = ["aram"]
edition = "2018"

[dependencies]
rand = "0.7.3"

[dependencies.sdl2]
version = "0.34.1"
default-features = false
features = ["ttf","image","gfx","mixer"]
